// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATlDb95WDY27RryRGwSNyEACCmH-OMZZs',
    appId: '1:917003188456:web:27495fecf189f2c22ab15d',
    messagingSenderId: '917003188456',
    projectId: 'todoapp-7328b',
    authDomain: 'todoapp-7328b.firebaseapp.com',
    storageBucket: 'todoapp-7328b.firebasestorage.app',
    measurementId: 'G-9LVCMYVR63',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIjRfyxpPgnyrag6lDauijelhKsSDHMM4',
    appId: '1:917003188456:android:00245ce65707241d2ab15d',
    messagingSenderId: '917003188456',
    projectId: 'todoapp-7328b',
    storageBucket: 'todoapp-7328b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCswq5I2UWe-pqvHSfjFarnv8XJWVSuqcw',
    appId: '1:917003188456:ios:b7b1455b8354aaf72ab15d',
    messagingSenderId: '917003188456',
    projectId: 'todoapp-7328b',
    storageBucket: 'todoapp-7328b.firebasestorage.app',
    iosBundleId: 'com.example.onboarddingScreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCswq5I2UWe-pqvHSfjFarnv8XJWVSuqcw',
    appId: '1:917003188456:ios:b7b1455b8354aaf72ab15d',
    messagingSenderId: '917003188456',
    projectId: 'todoapp-7328b',
    storageBucket: 'todoapp-7328b.firebasestorage.app',
    iosBundleId: 'com.example.onboarddingScreen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATlDb95WDY27RryRGwSNyEACCmH-OMZZs',
    appId: '1:917003188456:web:924d879a05847bce2ab15d',
    messagingSenderId: '917003188456',
    projectId: 'todoapp-7328b',
    authDomain: 'todoapp-7328b.firebaseapp.com',
    storageBucket: 'todoapp-7328b.firebasestorage.app',
    measurementId: 'G-ZV6SKLZQVJ',
  );
}
